[metadata]
name = conninfpy
version = 2.0.0
author = N.P. Bechtereva Institute of the Human Brain, Russian Academy of Sciences
author_email = ashish@ireddy.ru
description = Connectivity Inference Python (ConnInfPy) - Statistical analysis of brain connectivity networks
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/IHB-IBR-department/TFNBS
license = MIT
classifiers =
    Programming Language :: Python :: 3

[options]
package_dir =
    = .
packages = find:
python_requires = >=3.8
install_requires =
    numpy
    scipy
    matplotlib
    scikit-learn
    networkx
    mne
    pandas

[options.packages.find]
where = .

[options.extras_require]
dev =
    pytest
    sphinx
    sphinx-rtd-theme
